version: "3"
services:
    webscrapping:
        image: postgres
        container_name: webscrapping
        restart: always
        environment:
            POSTGRES_PASSWORD: admin
            POSTGRES_USER: admin
            POSTGRES_DB: webscrapping
        volumes:
            - ./data:/var/lib/postgresql/data
        ports:
            - 5432:5432
